import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Componentes de flutter'),
      ),
      body: ListView(
        children: const [
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
          Text('Hola Mundo'),
        ],
      ),
    );
  }
}
